//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkinglotOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        public string ID { get; set; }
        public System.DateTime Date { get; set; }
        public double Income { get; set; }
        public string HostID { get; set; }
    
        public virtual Host Host { get; set; }
    }
}
